// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cat_mash_api.Database;

#nullable disable

namespace cat_mash_api.Database.Migrations
{
    [DbContext(typeof(CatMashDbContext))]
    partial class CatMashDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("cat_mash_api.Database.Shared.EntityModels.Cat", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("id");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("image_url");

                    b.HasKey("Id");

                    b.ToTable("Cats");

                    b.HasData(
                        new
                        {
                            Id = "MTgwODA3MA",
                            ImageUrl = "http://24.media.tumblr.com/tumblr_m82woaL5AD1rro1o5o1_1280.jpg"
                        },
                        new
                        {
                            Id = "tt",
                            ImageUrl = "http://24.media.tumblr.com/tumblr_m29a9d62C81r2rj8po1_500.jpg"
                        },
                        new
                        {
                            Id = "bmp",
                            ImageUrl = "http://25.media.tumblr.com/tumblr_m4bgd9OXmw1qioo2oo1_500.jpg"
                        },
                        new
                        {
                            Id = "c8a",
                            ImageUrl = "http://24.media.tumblr.com/tumblr_lzxok2e2kX1qgjltdo1_1280.jpg"
                        },
                        new
                        {
                            Id = "3kj",
                            ImageUrl = "http://25.media.tumblr.com/tumblr_m33r7lpy361qzi9p6o1_500.jpg"
                        },
                        new
                        {
                            Id = "9pu",
                            ImageUrl = "http://25.media.tumblr.com/tumblr_m2p6dxhxul1qdvz31o1_500.jpg"
                        },
                        new
                        {
                            Id = "aca",
                            ImageUrl = "http://24.media.tumblr.com/tumblr_m1ku66jPWV1qze0hyo1_400.jpg"
                        },
                        new
                        {
                            Id = "ebk",
                            ImageUrl = "http://25.media.tumblr.com/tumblr_m4pwa9EXE41r6jd7fo1_500.jpg"
                        },
                        new
                        {
                            Id = "MTg0MTYyOQ",
                            ImageUrl = "http://25.media.tumblr.com/tumblr_m6x62cjEz31qk4s2co1_1280.jpg"
                        },
                        new
                        {
                            Id = "6mo",
                            ImageUrl = "http://25.media.tumblr.com/tumblr_lyj0y5tg4L1qbwemzo1_1280.jpg"
                        },
                        new
                        {
                            Id = "4m5",
                            ImageUrl = "http://25.media.tumblr.com/tumblr_m44w9nI50Y1qzyqubo1_500.jpg"
                        },
                        new
                        {
                            Id = "5v3",
                            ImageUrl = "http://24.media.tumblr.com/tumblr_lzqv50jiCj1qzex9io1_1280.jpg"
                        },
                        new
                        {
                            Id = "52k",
                            ImageUrl = "http://25.media.tumblr.com/tumblr_lrlhw46Re81r3q92to1_500.jpg"
                        },
                        new
                        {
                            Id = "47s",
                            ImageUrl = "http://25.media.tumblr.com/tumblr_m3u1mfIZwv1rtqthio1_500.jpg"
                        },
                        new
                        {
                            Id = "77s",
                            ImageUrl = "http://25.media.tumblr.com/Jjkybd3nS98hfqy8vevnj6R9_500.jpg"
                        },
                        new
                        {
                            Id = "8g6",
                            ImageUrl = "http://25.media.tumblr.com/tumblr_m4j6icIQdF1qzex9io1_1280.jpg"
                        },
                        new
                        {
                            Id = "6cu",
                            ImageUrl = "http://25.media.tumblr.com/5gI3dw08Qncg15r8LBMo8NMZo1_400.jpg"
                        },
                        new
                        {
                            Id = "71f",
                            ImageUrl = "http://24.media.tumblr.com/tumblr_lg1hnknXjm1qfyzelo1_1280.jpg"
                        },
                        new
                        {
                            Id = "2pp",
                            ImageUrl = "http://25.media.tumblr.com/tumblr_kstpz9IxDK1qzefipo1_250.gif"
                        },
                        new
                        {
                            Id = "e6d",
                            ImageUrl = "http://25.media.tumblr.com/tumblr_m4s05iYQmN1r6jd7fo1_500.gif"
                        },
                        new
                        {
                            Id = "99t",
                            ImageUrl = "http://24.media.tumblr.com/tumblr_m2gyauUXoh1qbe5pxo1_500.jpg"
                        },
                        new
                        {
                            Id = "510",
                            ImageUrl = "http://24.media.tumblr.com/tumblr_ltqi8k2OcP1qiyvcfo1_250.jpg"
                        },
                        new
                        {
                            Id = "9u3",
                            ImageUrl = "http://25.media.tumblr.com/tumblr_m20iu31nBD1qz4dkmo1_500.jpg"
                        },
                        new
                        {
                            Id = "1dp",
                            ImageUrl = "http://24.media.tumblr.com/tumblr_m11rjz2nrk1qznh2ao1_1280.jpg"
                        },
                        new
                        {
                            Id = "b8p",
                            ImageUrl = "http://25.media.tumblr.com/tumblr_luvlehQz7n1qgnva2o1_500.jpg"
                        },
                        new
                        {
                            Id = "7q3",
                            ImageUrl = "http://25.media.tumblr.com/tumblr_m2wvwmHrX61r73wdao1_250.gif"
                        },
                        new
                        {
                            Id = "8v5",
                            ImageUrl = "http://24.media.tumblr.com/tumblr_m0ljiiZ08O1r7plk4o1_500.jpg"
                        },
                        new
                        {
                            Id = "37p",
                            ImageUrl = "http://24.media.tumblr.com/tumblr_lw9hu39q621qdvbl3o1_1280.jpg"
                        },
                        new
                        {
                            Id = "2n0",
                            ImageUrl = "http://29.media.tumblr.com/tumblr_m1k4ze7hja1r6b7kmo1_500.jpg"
                        },
                        new
                        {
                            Id = "ckc",
                            ImageUrl = "http://24.media.tumblr.com/tumblr_lnvz6gLbjS1qji0t2o1_500.jpg"
                        },
                        new
                        {
                            Id = "27m",
                            ImageUrl = "http://27.media.tumblr.com/tumblr_lh6ywkF22D1qfyzelo1_1280.jpg"
                        },
                        new
                        {
                            Id = "di6",
                            ImageUrl = "http://25.media.tumblr.com/tumblr_m4rorb74ne1qkk65ko1_1280.jpg"
                        },
                        new
                        {
                            Id = "afr",
                            ImageUrl = "http://24.media.tumblr.com/tumblr_m44tfdCUcz1qzgoy8o1_1280.jpg"
                        },
                        new
                        {
                            Id = "65s",
                            ImageUrl = "http://24.media.tumblr.com/tumblr_luu4l5AmkP1qzxrnuo1_1280.jpg"
                        },
                        new
                        {
                            Id = "abs",
                            ImageUrl = "http://25.media.tumblr.com/tumblr_m1mls6SBfO1qze0hyo1_1280.jpg"
                        },
                        new
                        {
                            Id = "MjAxMTk1Mw",
                            ImageUrl = "http://24.media.tumblr.com/tumblr_mcg6abzbmT1qejbiro1_500.jpg"
                        },
                        new
                        {
                            Id = "6hn",
                            ImageUrl = "http://24.media.tumblr.com/tumblr_lqhtuoG1by1qbhms5o1_500.jpg"
                        },
                        new
                        {
                            Id = "e82",
                            ImageUrl = "http://25.media.tumblr.com/tumblr_m4rwuzEHVz1r6jd7fo1_1280.jpg"
                        },
                        new
                        {
                            Id = "bgf",
                            ImageUrl = "http://25.media.tumblr.com/tumblr_lgt0zjaTik1qgnva2o1_500.png"
                        },
                        new
                        {
                            Id = "93m",
                            ImageUrl = "http://25.media.tumblr.com/tumblr_lu8wwx12zx1qlyuwso1_1280.jpg"
                        },
                        new
                        {
                            Id = "MTY1Mjg5NQ",
                            ImageUrl = "http://25.media.tumblr.com/tumblr_m4vzekUu7G1r6b7kmo1_500.jpg"
                        },
                        new
                        {
                            Id = "3dr",
                            ImageUrl = "http://24.media.tumblr.com/tumblr_lvfpb18iea1qi23vmo1_500.jpg"
                        },
                        new
                        {
                            Id = "8o4",
                            ImageUrl = "http://25.media.tumblr.com/tumblr_lx6uh8RO4r1qenqklo1_1280.jpg"
                        },
                        new
                        {
                            Id = "8g1",
                            ImageUrl = "http://25.media.tumblr.com/tumblr_m3g4wzlmaK1qzex9io1_500.jpg"
                        },
                        new
                        {
                            Id = "3s9",
                            ImageUrl = "http://24.media.tumblr.com/tumblr_m3gl5xsZGq1r73wdao1_1280.jpg"
                        },
                        new
                        {
                            Id = "bjp",
                            ImageUrl = "http://24.media.tumblr.com/tumblr_m4l704E3mL1qdajm7o1_500.jpg"
                        },
                        new
                        {
                            Id = "cgp",
                            ImageUrl = "http://25.media.tumblr.com/tumblr_lql6c16YhH1qdth8zo1_1280.jpg"
                        },
                        new
                        {
                            Id = "1e6",
                            ImageUrl = "http://24.media.tumblr.com/tumblr_m0umerwZ3L1qznclro1_1280.jpg"
                        },
                        new
                        {
                            Id = "3b8",
                            ImageUrl = "http://24.media.tumblr.com/tumblr_m3pv11WNcO1r5c1jmo1_1280.jpg"
                        },
                        new
                        {
                            Id = "9us",
                            ImageUrl = "http://24.media.tumblr.com/tumblr_m1uu8abTLM1qd477zo1_500.jpg"
                        },
                        new
                        {
                            Id = "MTY4NDQ5NQ",
                            ImageUrl = "http://25.media.tumblr.com/tumblr_m4apapdhVj1r18oqso1_500.jpg"
                        },
                        new
                        {
                            Id = "bu5",
                            ImageUrl = "http://25.media.tumblr.com/tumblr_m3gaff05EE1qddbvio1_500.jpg"
                        },
                        new
                        {
                            Id = "3ic",
                            ImageUrl = "http://24.media.tumblr.com/tumblr_m3nbobox8B1qj638ro1_1280.jpg"
                        },
                        new
                        {
                            Id = "8q",
                            ImageUrl = "http://25.media.tumblr.com/tumblr_llahls2IeS1qjmniro1_250.gif"
                        },
                        new
                        {
                            Id = "ck8",
                            ImageUrl = "http://24.media.tumblr.com/tumblr_lnvyrt5j1M1qce7tgo1_500.gif"
                        },
                        new
                        {
                            Id = "s7",
                            ImageUrl = "http://30.media.tumblr.com/tumblr_m2b0ykP6Fu1qzex9io1_1280.jpg"
                        },
                        new
                        {
                            Id = "is",
                            ImageUrl = "http://29.media.tumblr.com/tumblr_ly4w9oJVgE1r189uao1_500.jpg"
                        },
                        new
                        {
                            Id = "2r3",
                            ImageUrl = "http://28.media.tumblr.com/qgIb8tERiqzchkc2UFsyedLmo1_500.jpg"
                        },
                        new
                        {
                            Id = "btv",
                            ImageUrl = "http://25.media.tumblr.com/tumblr_m4habeFR271qd477zo1_1280.jpg"
                        },
                        new
                        {
                            Id = "e3a",
                            ImageUrl = "http://25.media.tumblr.com/tumblr_m20bftDngo1qejbiro1_1280.jpg"
                        },
                        new
                        {
                            Id = "al8",
                            ImageUrl = "http://24.media.tumblr.com/tumblr_lehgc4thel1qecpy9o1_500.gif"
                        },
                        new
                        {
                            Id = "56s",
                            ImageUrl = "http://25.media.tumblr.com/tumblr_kqai1e03j91qzv5pwo1_500.jpg"
                        },
                        new
                        {
                            Id = "aj6",
                            ImageUrl = "http://24.media.tumblr.com/tumblr_ku726anOmb1qzrlhgo1_500.png"
                        },
                        new
                        {
                            Id = "46h",
                            ImageUrl = "http://25.media.tumblr.com/tumblr_m3tpx8fsXX1qhwmnpo1_400.jpg"
                        },
                        new
                        {
                            Id = "bd8",
                            ImageUrl = "http://25.media.tumblr.com/tumblr_lhe1fu7JpG1qgnva2o1_500.png"
                        },
                        new
                        {
                            Id = "45k",
                            ImageUrl = "http://24.media.tumblr.com/tumblr_m43mq45fgs1qzxrnuo1_1280.jpg"
                        },
                        new
                        {
                            Id = "bjc",
                            ImageUrl = "http://25.media.tumblr.com/tumblr_m4mo17vXSa1r6jd7fo1_500.jpg"
                        },
                        new
                        {
                            Id = "5ts",
                            ImageUrl = "http://25.media.tumblr.com/tumblr_m1oyzmlqEu1rsf53jo1_1280.jpg"
                        },
                        new
                        {
                            Id = "chk",
                            ImageUrl = "http://25.media.tumblr.com/tumblr_lpl0cy8o5R1qdth8zo1_1280.jpg"
                        },
                        new
                        {
                            Id = "ca8",
                            ImageUrl = "http://24.media.tumblr.com/tumblr_lz5pu74OPk1qgjltdo1_1280.jpg"
                        },
                        new
                        {
                            Id = "MTU0NzgwMA",
                            ImageUrl = "http://25.media.tumblr.com/tumblr_m7cjk9zTNM1qzex9io1_1280.jpg"
                        },
                        new
                        {
                            Id = "ddp",
                            ImageUrl = "http://25.media.tumblr.com/tumblr_m4gtikn86b1qztc0jo1_1280.jpg"
                        },
                        new
                        {
                            Id = "e03",
                            ImageUrl = "http://25.media.tumblr.com/tumblr_m2xlwaadCC1qejbiro1_1280.jpg"
                        },
                        new
                        {
                            Id = "9mk",
                            ImageUrl = "http://24.media.tumblr.com/GxlDeM8kxl6gszkaC1RgD776o1_1280.jpg"
                        },
                        new
                        {
                            Id = "3gm",
                            ImageUrl = "http://25.media.tumblr.com/tumblr_m3khmzDXEo1qjc1a7o1_1280.jpg"
                        },
                        new
                        {
                            Id = "6lo",
                            ImageUrl = "http://25.media.tumblr.com/tumblr_lz8fwef0VA1qzv52ko1_1280.jpg"
                        },
                        new
                        {
                            Id = "MjA2NTY1NQ",
                            ImageUrl = "http://25.media.tumblr.com/tumblr_ma7j0aGNbB1r6jd7fo1_1280.jpg"
                        },
                        new
                        {
                            Id = "41c",
                            ImageUrl = "http://25.media.tumblr.com/tumblr_m3pm45zC4v1qjahcpo1_500.jpg"
                        },
                        new
                        {
                            Id = "54m",
                            ImageUrl = "http://25.media.tumblr.com/tumblr_lqv93f3ZQT1qi3974o1_500.jpg"
                        },
                        new
                        {
                            Id = "bjf",
                            ImageUrl = "http://24.media.tumblr.com/tumblr_m2lim4Wocd1qjev1to1_1280.jpg"
                        },
                        new
                        {
                            Id = "e9h",
                            ImageUrl = "http://25.media.tumblr.com/tumblr_m4qdjuybqb1r0wqrdo1_1280.jpg"
                        },
                        new
                        {
                            Id = "ec6",
                            ImageUrl = "http://25.media.tumblr.com/tumblr_m4pvakprVF1r6jd7fo1_500.jpg"
                        },
                        new
                        {
                            Id = "4ge",
                            ImageUrl = "http://25.media.tumblr.com/tumblr_m2g2ksSLML1qgkc80o1_400.gif"
                        },
                        new
                        {
                            Id = "ds4",
                            ImageUrl = "http://25.media.tumblr.com/tumblr_m3uxadNlfI1qejbiro1_1280.jpg"
                        },
                        new
                        {
                            Id = "MTcwMTgxMg",
                            ImageUrl = "http://25.media.tumblr.com/tumblr_mc1lz78RNn1qjc1a7o1_1280.jpg"
                        },
                        new
                        {
                            Id = "7ts",
                            ImageUrl = "http://24.media.tumblr.com/tumblr_lht68lybsE1qcn249o1_250.gif"
                        },
                        new
                        {
                            Id = "d5c",
                            ImageUrl = "http://25.media.tumblr.com/tumblr_lidvsekFL91qzabkfo1_1280.jpg"
                        },
                        new
                        {
                            Id = "6jf",
                            ImageUrl = "http://25.media.tumblr.com/tumblr_lpcq3447RK1qbhms5o1_500.jpg"
                        },
                        new
                        {
                            Id = "MTY4MDkyOA",
                            ImageUrl = "http://25.media.tumblr.com/tumblr_mbe1tuRvoN1rxer0vo1_1280.jpg"
                        },
                        new
                        {
                            Id = "8hk",
                            ImageUrl = "http://25.media.tumblr.com/tumblr_m47yaokX791qhwmnpo1_500.jpg"
                        },
                        new
                        {
                            Id = "5no",
                            ImageUrl = "http://24.media.tumblr.com/tumblr_ll3uw0KDeM1qb8a3ro1_500.jpg"
                        },
                        new
                        {
                            Id = "e3v",
                            ImageUrl = "http://24.media.tumblr.com/tumblr_m1nn0aPJU31qejbiro1_1280.jpg"
                        },
                        new
                        {
                            Id = "dp",
                            ImageUrl = "http://28.media.tumblr.com/tumblr_ly7rtpsCSc1qgop81o1_1280.jpg"
                        },
                        new
                        {
                            Id = "6jt",
                            ImageUrl = "http://24.media.tumblr.com/tumblr_lowyfwTewp1qbhms5o1_500.jpg"
                        },
                        new
                        {
                            Id = "1qj",
                            ImageUrl = "http://27.media.tumblr.com/tumblr_lwaso5dl5N1qbhms5o1_500.jpg"
                        },
                        new
                        {
                            Id = "5io",
                            ImageUrl = "http://25.media.tumblr.com/tumblr_lst9zbbAGx1r4xjo2o1_1280.jpg"
                        },
                        new
                        {
                            Id = "46o",
                            ImageUrl = "http://25.media.tumblr.com/tumblr_m44vnvR00W1rtuomto1_1280.jpg"
                        },
                        new
                        {
                            Id = "4lt",
                            ImageUrl = "http://24.media.tumblr.com/tumblr_kujwmnKr8k1qzpwi0o1_250.gif"
                        },
                        new
                        {
                            Id = "6ps",
                            ImageUrl = "http://25.media.tumblr.com/tumblr_lwip0fnA2D1qzv52ko1_1280.jpg"
                        },
                        new
                        {
                            Id = "a4e",
                            ImageUrl = "http://25.media.tumblr.com/tumblr_m3jbdxqnma1qa8o34o1_500.jpg"
                        });
                });

            modelBuilder.Entity("cat_mash_api.Database.Shared.EntityModels.Vote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("CatId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("cat_id");

                    b.HasKey("Id");

                    b.HasIndex("CatId");

                    b.ToTable("Votes");
                });

            modelBuilder.Entity("cat_mash_api.Database.Shared.EntityModels.Vote", b =>
                {
                    b.HasOne("cat_mash_api.Database.Shared.EntityModels.Cat", "Cat")
                        .WithMany("Votes")
                        .HasForeignKey("CatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cat");
                });

            modelBuilder.Entity("cat_mash_api.Database.Shared.EntityModels.Cat", b =>
                {
                    b.Navigation("Votes");
                });
#pragma warning restore 612, 618
        }
    }
}
